name: entrega_hub
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.3.0
  image: ^4.2.0
  get: ^4.6.6
  flutter_svg: ^2.0.11
  get_storage: ^2.1.1
  image_picker: ^1.1.2
  uuid: ^4.5.1
  fluttertoast: ^8.2.8
  photo_manager: ^3.6.2
  shared_preferences: ^2.3.3
  dio: ^5.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  saver_gallery: ^4.0.0
  permission_handler: ^10.2.0
  qr_bar_code_scanner_dialog:
    git:
      url: https://github.com/MikaelDDavidd/qr-bar-code-scanner-dialog.git
      ref: master

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/ic/